/**
 * Dziennik zmian „na brudno”.
 *
 * Każda zmiana widoczna dla użytkowników dostaje tu jeden wpis (w tym samym commicie co kod).
 * Serwer codziennie o 23:30 (czas polski) publikuje wpisy z danego dnia w zakładce „Dziennik zmian”.
 * Wpisy z wcześniejszych dni, których jeszcze nie opublikowano, pojawiają się od razu po wdrożeniu.
 *
 * Zasady pisania:
 * - każdy wpis ma dwie wersje językowe: `text` po polsku i `textEn` po angielsku (to samo zdanie, nie skrót),
 * - jedno zdanie z perspektywy użytkownika („Możesz teraz…” / “You can now…”),
 * - bez szczegółów technicznych (nazwy plików, API, baza danych),
 * - nazwy przycisków i zakładek w `textEn` tak jak w angielskiej wersji interfejsu (src/i18n/en),
 * - `area` po polsku; angielska nazwa pochodzi z CHANGELOG_AREAS_EN (nowy obszar = nowa pozycja w mapie),
 * - `id` musi być unikalne i nie może się zmieniać (po nim serwer rozpoznaje wpis),
 * - poprawienie tekstu już opublikowanego wpisu zaktualizuje go w dzienniku.
 */

export type ChangelogType = 'new' | 'improved' | 'fixed';

export interface ChangelogDraft {
  id: string;
  /** Dzień zmiany (czas polski), RRRR-MM-DD. */
  day: string;
  type: ChangelogType;
  /** Część aplikacji po polsku, np. „Talie”, „Kolekcja” (musi być w CHANGELOG_AREAS_EN). */
  area?: string;
  /** Opis po polsku. */
  text: string;
  /** Ten sam opis po angielsku. */
  textEn: string;
}

/** Angielskie nazwy części aplikacji (klucz: polska nazwa z pola `area`). */
export const CHANGELOG_AREAS_EN: Record<string, string> = {
  Aplikacja: 'App',
  'Dziennik zmian': 'Changelog',
  Gracze: 'Players',
  Import: 'Import',
  Karty: 'Cards',
  Kolekcja: 'Collection',
  Konto: 'Account',
  'Lista życzeń': 'Wishlist',
  Logowanie: 'Login',
  Pomoc: 'Help',
  Skaner: 'Scanner',
  Spoilery: 'Spoilers',
  Sprzedam: 'For sale',
  Statystyki: 'Statistics',
  Talie: 'Decks',
  Telefon: 'Mobile',
  Udostępnianie: 'Sharing',
  Ustawienia: 'Settings',
  Wiadomości: 'Messages',
  Wygląd: 'Appearance'
};

export const CHANGELOG_DRAFTS: ChangelogDraft[] = [
  // ---------- 10 października 2026 ----------
  { id: '2026-10-10-talie-spolecznosci', day: '2026-10-10', type: 'new', area: 'Talie', text: 'Nowa zakładka „Talie społeczności” pokazuje talie, które inni gracze udostępnili publicznym linkiem, z wyszukiwaniem po nazwie, dowódcy lub autorze i podziałem na formaty.', textEn: 'The new “Community decks” tab shows decks other players have shared with a public link, with search by name, commander or author and a split by format.' },
  // ---------- 9 października 2026 ----------
  { id: '2026-10-09-ko-fi', day: '2026-10-09', type: 'improved', area: 'Aplikacja', text: 'Przycisk „Postaw kawę” zastąpił przycisk „Wesprzyj mnie na Ko-fi”, przez który możesz wesprzeć rozwój Mana Screw.', textEn: 'The “Buy me a coffee” button has been replaced with “Support me on Ko-fi”, which you can use to support the development of Mana Screw.' },
  { id: '2026-10-09-waluta-od-razu', day: '2026-10-09', type: 'fixed', area: 'Ustawienia', text: 'Zmiana waluty, źródła cen lub kursów w ustawieniach od razu przelicza wartość kolekcji i wszystkie ceny, bez osobnego zapisywania.', textEn: 'Changing the currency, price source or exchange rates in Settings now instantly recalculates your collection value and all prices, with no separate save step.' },
  { id: '2026-10-09-ustawienia-nie-znikaja', day: '2026-10-09', type: 'fixed', area: 'Ustawienia', text: 'Zmiana ustawień wyceny nie przywraca już domyślnej liczby wierszy w kolekcji ani rozmiaru podglądu kart w talii.', textEn: 'Changing pricing settings no longer resets the number of rows in your collection or the card preview size in decks.' },
  { id: '2026-10-09-dziennik-po-angielsku', day: '2026-10-09', type: 'improved', area: 'Dziennik zmian', text: 'Dziennik zmian jest teraz wyświetlany w wybranym języku, także po angielsku.', textEn: 'The changelog is now shown in your chosen language, including English.' },
  { id: '2026-10-09-wersja-angielska', day: '2026-10-09', type: 'new', area: 'Ustawienia', text: 'Aplikacja jest teraz dostępna także po angielsku: język zmienisz flagami obok ikony Discorda, a wybór zapisuje się na Twoim profilu.', textEn: 'The app is now also available in English: switch the language with the flags next to the Discord icon, and your choice is saved to your profile.' },
  // ---------- 8 października 2026 ----------
  { id: '2026-10-08-spoilery-kolejnosc', day: '2026-10-08', type: 'improved', area: 'Spoilery', text: 'Zakładka „Spoilery” pokazuje już tylko dodatki przed premierą, ułożone od najbliższej daty wydania.', textEn: 'The “Spoilers” tab now shows only sets that haven’t been released yet, sorted from the nearest release date.' },
  { id: '2026-10-08-zakladka-spoilery', day: '2026-10-08', type: 'new', area: 'Spoilery', text: 'Nowa zakładka „Spoilery” pokazuje zapowiedziane karty z nadchodzących dodatków, z podziałem na kategorie, filtrami i możliwością dodania karty do listy życzeń.', textEn: 'The new “Spoilers” tab shows previewed cards from upcoming sets, grouped into categories, with filters and the option to add a card to your wishlist.' },
  { id: '2026-10-08-nowy-ekran-logowania', day: '2026-10-08', type: 'improved', area: 'Logowanie', text: 'Ekran logowania jest prostszy i czytelniejszy, a wpisane hasło możesz podejrzeć przyciskiem „Pokaż”.', textEn: 'The login screen is simpler and easier to read, and you can reveal the password you typed with the “Show” button.' },
  { id: '2026-10-08-kolekcja-strony', day: '2026-10-08', type: 'new', area: 'Kolekcja', text: 'Kolekcja jest teraz podzielona na strony, a liczbę wierszy kart na stronie (12, 24, 48 lub 60) wybierasz sam i zostaje zapamiętana na Twoim koncie.', textEn: 'Your collection is now split into pages, and you choose how many rows of cards to show per page (12, 24, 48 or 60); the choice is remembered on your account.' },
  { id: '2026-10-08-wczytywanie-katalogu', day: '2026-10-08', type: 'improved', area: 'Kolekcja', text: 'Przejście do katalogu z dużą liczbą kart pokazuje teraz pasek wczytywania zamiast chwilowego zawieszenia strony.', textEn: 'Opening a binder with lots of cards now shows a loading bar instead of the page briefly freezing.' },
  { id: '2026-10-08-stats-bez-basic-lands', day: '2026-10-08', type: 'improved', area: 'Statystyki', text: 'Wykres kolorów i krzywa many w Statystykach nie wliczają już lądów.', textEn: 'The colour chart and mana curve in Statistics no longer count lands.' },
  { id: '2026-10-08-stats-najcenniejsze-sztuka', day: '2026-10-08', type: 'improved', area: 'Statystyki', text: 'Najcenniejsze karty są teraz układane według ceny jednej sztuki, niezależnie od liczby posiadanych egzemplarzy.', textEn: 'Most valuable cards are now ranked by the price of a single copy, regardless of how many copies you own.' },
  { id: '2026-10-08-stats-historia', day: '2026-10-08', type: 'new', area: 'Statystyki', text: 'Pod największymi zmianami cen widać teraz historię wartości kolekcji i liczby kart dzień po dniu.', textEn: 'Below the biggest movers you can now see your collection’s value and card count history, day by day.' },
  { id: '2026-10-08-discord', day: '2026-10-08', type: 'new', area: 'Aplikacja', text: 'Obok przycisku „Postaw kawę” jest teraz ikonka Discorda, która prowadzi na serwer społeczności Mana Screw.', textEn: 'Next to the “Buy me a coffee” button there is now a Discord icon that takes you to the Mana Screw community server.' },
  { id: '2026-10-08-stopka-regulamin', day: '2026-10-08', type: 'new', area: 'Aplikacja', text: 'Na dole strony pojawiła się stopka z numerem wersji aplikacji i regulaminem serwisu, w tym zasadami handlu między graczami.', textEn: 'A footer at the bottom of the page now shows the app version number and the terms of service, including the rules for trading between players.' },
  { id: '2026-10-08-automatyczna-aktualizacja', day: '2026-10-08', type: 'improved', area: 'Aplikacja', text: 'Aplikacja sama przechodzi na najnowszą wersję przy zmianie zakładki, bez ręcznego odświeżania strony.', textEn: 'The app now updates itself to the latest version when you switch tabs, with no need to refresh the page manually.' },
  { id: '2026-10-08-collection-unit-price', day: '2026-10-08', type: 'improved', area: 'Kolekcja', text: 'Przy kartach posiadanych w kilku egzemplarzach widać teraz obok łącznej wartości także cenę za sztukę.', textEn: 'For cards you own several copies of, the price per copy is now shown next to the total value.' },
  { id: '2026-10-08-collection-loading', day: '2026-10-08', type: 'improved', area: 'Kolekcja', text: 'Duża kolekcja otwiera się płynniej, a w trakcie wczytywania widać pasek postępu z liczbą przygotowanych kart.', textEn: 'Large collections open more smoothly, and while loading you can see a progress bar with the number of cards prepared.' },

  // ---------- 2 października 2026 ----------
  { id: '2026-10-02-scanner-local', day: '2026-10-02', type: 'new', area: 'Skaner', text: 'Nowy skaner kart w przeglądarce: sam wykrywa kartę, prostuje zdjęcie i rozpoznaje ją po grafice i numerze.', textEn: 'A new in-browser card scanner: it detects the card on its own, straightens the photo and recognises it by its artwork and collector number.' },
  { id: '2026-10-02-scanner-continuous', day: '2026-10-02', type: 'new', area: 'Skaner', text: 'Tryb ciągły skanera do szybkiego dodawania całych stosów kart.', textEn: 'Continuous scanner mode for quickly adding whole stacks of cards.' },
  { id: '2026-10-02-mobile-nav', day: '2026-10-02', type: 'new', area: 'Telefon', text: 'Wygodniejsza wersja na telefon: dolny pasek nawigacji, kolekcja jako lista i okna wysuwane od dołu.', textEn: 'A more comfortable mobile version: a bottom navigation bar, the collection as a list and windows that slide up from the bottom.' },
  { id: '2026-10-02-pwa', day: '2026-10-02', type: 'new', area: 'Telefon', text: 'Mana Screw możesz dodać do ekranu głównego telefonu i uruchamiać jak aplikację.', textEn: 'You can add Mana Screw to your phone’s home screen and launch it like an app.' },
  { id: '2026-10-02-back-button', day: '2026-10-02', type: 'fixed', area: 'Telefon', text: 'Przycisk i gest „Wstecz” zamyka otwarte okno zamiast opuszczać stronę.', textEn: 'The “Back” button and gesture now close the open window instead of leaving the page.' },
  { id: '2026-10-02-sellers-map', day: '2026-10-02', type: 'new', area: 'Gracze', text: 'Mapa sprzedawców i miejscowość w profilu: zobacz, kto w okolicy sprzedaje karty.', textEn: 'Sellers map and a town in your profile: see who nearby is selling cards.' },
  { id: '2026-10-02-wishlist-link', day: '2026-10-02', type: 'new', area: 'Lista życzeń', text: 'Publiczny link do listy życzeń, który możesz wysłać znajomym.', textEn: 'A public wishlist link you can send to your friends.' },
  { id: '2026-10-02-value-change', day: '2026-10-02', type: 'improved', area: 'Kolekcja', text: 'Nagłówek pokazuje zmianę wartości kolekcji od ostatniego odświeżenia cen.', textEn: 'The header shows the change in your collection’s value since the last price refresh.' },
  { id: '2026-10-02-settings', day: '2026-10-02', type: 'new', area: 'Ustawienia', text: 'Ustawienia w osobnej zakładce: zmiana hasła, wylogowanie ze wszystkich urządzeń i usunięcie konta.', textEn: 'Settings now have their own tab: change your password, log out of all devices and delete your account.' },
  { id: '2026-10-02-deck-stats', day: '2026-10-02', type: 'new', area: 'Talie', text: 'Statystyki talii: losowa ręka startowa, szanse dociągnięcia i wymagania kolorów many.', textEn: 'Deck statistics: a random opening hand, draw odds and mana colour requirements.' },
  { id: '2026-10-02-edhrec', day: '2026-10-02', type: 'new', area: 'Talie', text: 'Sugestie kart z EDHREC dla talii Commander.', textEn: 'Card suggestions from EDHREC for Commander decks.' },
  { id: '2026-10-02-deck-links', day: '2026-10-02', type: 'new', area: 'Talie', text: 'Publiczne linki do talii: każdy z linkiem zobaczy talię bez logowania.', textEn: 'Public deck links: anyone with the link can view the deck without logging in.' },
  { id: '2026-10-02-for-sale-binder', day: '2026-10-02', type: 'improved', area: 'Kolekcja', text: 'Karty oznaczone na sprzedaż trafiają do osobnej kategorii „Sprzedam”.', textEn: 'Cards marked for sale go into a separate “For sale” category.' },
  { id: '2026-10-02-edit-save', day: '2026-10-02', type: 'fixed', area: 'Kolekcja', text: 'Edycja pozycji w kolekcji znów zapisuje się poprawnie.', textEn: 'Editing a collection entry saves correctly again.' },

  // ---------- 4 października 2026 ----------
  { id: '2026-10-04-login-page', day: '2026-10-04', type: 'new', area: 'Logowanie', text: 'Nowa strona startowa z kartami dnia i opisem wszystkich funkcji.', textEn: 'A new start page with cards of the day and a description of all features.' },
  { id: '2026-10-04-ui-refresh', day: '2026-10-04', type: 'improved', area: 'Wygląd', text: 'Odświeżony wygląd całej aplikacji: czytelniejsze teksty, nowy nagłówek z zakładkami w jednej linii i menu konta.', textEn: 'A refreshed look across the whole app: more readable text, a new header with tabs on a single line and an account menu.' },
  { id: '2026-10-04-deck-colors', day: '2026-10-04', type: 'improved', area: 'Talie', text: 'Nowa sekcja kolorów many z podglądem kart, o których mówią podpowiedzi.', textEn: 'A new mana colour section with previews of the cards the tips refer to.' },
  { id: '2026-10-04-basic-lands', day: '2026-10-04', type: 'new', area: 'Talie', text: 'Szybkie dodawanie Basic Lands w kolorach dowódcy.', textEn: 'Quickly add Basic Lands in your commander’s colours.' },
  { id: '2026-10-04-tokens', day: '2026-10-04', type: 'new', area: 'Talie', text: 'Sekcja „Tokeny” z tokenami, które tworzą karty w talii.', textEn: 'A “Tokens” section listing the tokens created by the cards in your deck.' },
  { id: '2026-10-04-replace', day: '2026-10-04', type: 'new', area: 'Talie', text: 'Przycisk „Zastąp” w sugestiach EDHREC: wybierz kartę z talii, którą zamienisz na polecaną.', textEn: 'A “Replace” button in EDHREC suggestions: pick a card from your deck to swap for the recommended one.' },
  { id: '2026-10-04-legality', day: '2026-10-04', type: 'new', area: 'Talie', text: 'Sprawdzanie legalności w Commanderze: niedozwolone karty są podświetlone na czerwono z wyjaśnieniem.', textEn: 'Commander legality checks: cards that aren’t allowed are highlighted in red with an explanation.' },
  { id: '2026-10-04-version-picker', day: '2026-10-04', type: 'new', area: 'Talie', text: 'Przy dodawaniu karty do talii wybierasz wydanie i wersję foil.', textEn: 'When adding a card to a deck, you choose the printing and the foil version.' },
  { id: '2026-10-04-deck-sorting', day: '2026-10-04', type: 'improved', area: 'Talie', text: 'Kategorie talii układają się w czterech kolumnach, a karty możesz sortować po nazwie, koszcie many lub kolorze.', textEn: 'Deck categories are laid out in four columns, and you can sort cards by name, mana cost or colour.' },
  { id: '2026-10-04-deck-value', day: '2026-10-04', type: 'fixed', area: 'Talie', text: 'Wartość talii na kafelku zgadza się z wartością w widoku talii (uwzględnia foile).', textEn: 'The deck value on the tile now matches the value in the deck view (foils included).' },
  { id: '2026-10-04-deck-to-binder', day: '2026-10-04', type: 'new', area: 'Talie', text: 'Przycisk na kafelku talii kopiuje wszystkie jej karty, w tych samych wersjach, do domyślnego klasera.', textEn: 'A button on the deck tile copies all of its cards, in the same printings, into your default binder.' },
  { id: '2026-10-04-japanese', day: '2026-10-04', type: 'new', area: 'Karty', text: 'Japońskie wersje kart, także Basic Lands, do wyboru przy dodawaniu.', textEn: 'Japanese card versions, including Basic Lands, to choose from when adding cards.' },
  { id: '2026-10-04-bracket', day: '2026-10-04', type: 'new', area: 'Talie', text: 'Oznaczenie Game Changers na kartach i szacowany bracket talii (dane z Commander Spellbook).', textEn: 'Game Changers are marked on cards and decks get an estimated bracket (data from Commander Spellbook).' },
  { id: '2026-10-04-anti-spam', day: '2026-10-04', type: 'improved', area: 'Wiadomości', text: 'Ochrona przed spamem w wiadomościach i możliwość blokowania użytkowników.', textEn: 'Spam protection in messages and the option to block users.' },
  { id: '2026-10-04-history-chart', day: '2026-10-04', type: 'new', area: 'Kolekcja', text: 'Kliknij wartość kolekcji w nagłówku, aby zobaczyć wykres wartości i liczby kart z 7 dni, miesiąca lub roku.', textEn: 'Click the collection value in the header to see a chart of its value and card count over 7 days, a month or a year.' },
  { id: '2026-10-04-wishlist-map', day: '2026-10-04', type: 'new', area: 'Lista życzeń', text: 'Przycisk „Mapa sprzedawców” na liście życzeń.', textEn: 'A “Sellers map” button on the wishlist.' },
  { id: '2026-10-04-message-seller', day: '2026-10-04', type: 'new', area: 'Sprzedam', text: 'Przycisk „Napisz do sprzedawcy” w profilu gracza i w publicznej ofercie sprzedaży.', textEn: 'A “Message the seller” button on player profiles and on public sale offers.' },
  { id: '2026-10-04-pretty-links', day: '2026-10-04', type: 'improved', area: 'Udostępnianie', text: 'Krótsze linki do talii i ofert (np. manascrew.eu/sprzedam/nazwa) z ładnym podglądem po wklejeniu w komunikatorze.', textEn: 'Shorter links to decks and offers (e.g. manascrew.eu/sprzedam/name) with a nice preview when pasted into a messenger.' },
  { id: '2026-10-04-logo', day: '2026-10-04', type: 'improved', area: 'Wygląd', text: 'Nowe logo aplikacji.', textEn: 'A new app logo.' },
  { id: '2026-10-04-coffee', day: '2026-10-04', type: 'new', text: 'Przycisk „Postaw kawę”, jeśli chcesz wesprzeć rozwój Mana Screw.', textEn: 'A “Buy me a coffee” button if you’d like to support the development of Mana Screw.' },

  // ---------- 5 października 2026 ----------
  { id: '2026-10-05-top-movers', day: '2026-10-05', type: 'improved', area: 'Statystyki', text: 'Nowa sekcja „Największe zmiany”: 20 kart z kolekcji, które najbardziej zyskały, i 20, które najbardziej straciły od ostatniego odświeżenia cen.', textEn: 'A new “Biggest movers” section: the 20 cards in your collection that gained the most and the 20 that lost the most since the last price refresh.' },
  { id: '2026-10-05-changelog', day: '2026-10-05', type: 'new', area: 'Dziennik zmian', text: 'Zakładka „Dziennik zmian”: codziennie o 23:30 pojawia się tu podsumowanie nowości z danego dnia.', textEn: 'The “Changelog” tab: every day at 23:30 a summary of that day’s changes appears here.' },
  { id: '2026-10-05-unread-mail', day: '2026-10-05', type: 'improved', area: 'Wiadomości', text: 'Nowe wiadomości pojawiają się bez odświeżania strony: koperta podświetla się na bursztynowo, na telefonie pojawia się w nagłówku, a liczbę nieprzeczytanych widać też w tytule karty przeglądarki.', textEn: 'New messages appear without refreshing the page: the envelope lights up amber, on phones it shows up in the header, and the unread count is also shown in the browser tab title.' },
  { id: '2026-10-05-wishlist-match-label', day: '2026-10-05', type: 'fixed', area: 'Gracze', text: 'Kafelek gracza jasno rozróżnia karty z Twojej listy życzeń, które sprzedaje, od tych, które ma tylko w kolekcji.', textEn: 'A player’s tile now clearly distinguishes cards from your wishlist that they are selling from those they only have in their collection.' },
  { id: '2026-10-05-set-share', day: '2026-10-05', type: 'improved', area: 'Kolekcja', text: 'Lista dodatków w filtrze kolekcji pokazuje, ile różnych kart z dodatku masz, np. 45/269 (16%), i jest ułożona od najnowszego dodatku.', textEn: 'The set list in the collection filter shows how many different cards from each set you own, e.g. 45/269 (16%), sorted from the newest set.' },
  { id: '2026-10-05-bug-report', day: '2026-10-05', type: 'new', area: 'Pomoc', text: 'Zgłoś błąd z menu konta: opisz problem i dołącz zrzut ekranu (z pliku albo wklejony skrótem Ctrl+V).', textEn: 'Report a bug from the account menu: describe the problem and attach a screenshot (from a file or pasted with Ctrl+V).' },
  { id: '2026-10-05-phyrexian', day: '2026-10-05', type: 'new', area: 'Karty', text: 'Karty w języku phyrexian w bazie kart, do wyboru przy dodawaniu i jako język karty w kolekcji.', textEn: 'Phyrexian-language cards in the card database, available when adding cards and as a card language in your collection.' },
  { id: '2026-10-05-import-progress', day: '2026-10-05', type: 'improved', area: 'Import', text: 'Pasek postępu przy imporcie kolekcji: przy dużych listach (np. kilka tysięcy kart) widać, ile kart już rozpoznano i zapisano.', textEn: 'A progress bar when importing a collection: with large lists (e.g. several thousand cards) you can see how many cards have already been recognised and saved.' },
  { id: '2026-10-05-suggestion-wishlist', day: '2026-10-05', type: 'improved', area: 'Talie', text: 'W sugestiach EDHREC przycisk z sercem dodaje kartę do listy życzeń; karty, które już na niej są, mają wypełnione serce.', textEn: 'In EDHREC suggestions the heart button adds a card to your wishlist; cards already on it have a filled heart.' },
  { id: '2026-10-05-suggestion-regular-print', day: '2026-10-05', type: 'improved', area: 'Talie', text: 'Sugestie EDHREC pokazują najnowsze zwykłe wydanie karty zamiast Secret Lair, promek czy wersji borderless i showcase.', textEn: 'EDHREC suggestions show the newest regular printing of a card instead of Secret Lair, promos or borderless and showcase versions.' },
  { id: '2026-10-05-dfc-thumbs', day: '2026-10-05', type: 'fixed', area: 'Karty', text: 'Miniatury kart dwustronnych (np. przy wyborze dowódcy, w talii i w wyszukiwarce) wczytują się poprawnie.', textEn: 'Thumbnails of double-faced cards (e.g. when choosing a commander, in decks and in search) load correctly.' },
  { id: '2026-10-05-for-sale-add', day: '2026-10-05', type: 'new', area: 'Sprzedam', text: 'Przycisk „Dodaj kartę na sprzedaż”: wyszukaj dowolną kartę, wybierz wydanie, foil, ilość, stan i cenę, a trafi od razu do Twojej oferty.', textEn: 'An “Add a card for sale” button: search for any card, choose the printing, foil, quantity, condition and price, and it goes straight into your offer.' },
  { id: '2026-10-05-print-filter', day: '2026-10-05', type: 'improved', area: 'Karty', text: 'Przy wyborze wydania karty możesz wpisać kod dodatku i numer z dołu karty (np. DSC 114), aby od razu znaleźć właściwą wersję.', textEn: 'When choosing a card’s printing you can type the set code and the number from the bottom of the card (e.g. DSC 114) to find the right version straight away.' },
  { id: '2026-10-05-delete-main-binder', day: '2026-10-05', type: 'fixed', area: 'Kolekcja', text: 'Jasne ostrzeżenie przy usuwaniu klasera: usunięcie głównego klasera usuwa jego karty (poza wystawionymi na sprzedaż), a usunięcie innego przenosi karty do głównego.', textEn: 'A clear warning when deleting a binder: deleting the main binder removes its cards (except those listed for sale), while deleting any other binder moves its cards to the main one.' },

  // ---------- 8 października 2026 ----------
  { id: '2026-10-08-separate-entries', day: '2026-10-08', type: 'fixed', area: 'Kolekcja', text: 'Karty różniące się wydaniem, wersją foil, stanem, językiem lub klaserem są w kolekcji osobnymi pozycjami, a dodanie innej wersji nie zmienia już posiadanej karty.', textEn: 'Cards that differ in printing, foil, condition, language or binder are now separate entries in your collection, and adding a different version no longer changes a card you already own.' },
  { id: '2026-10-08-catalog-create-error', day: '2026-10-08', type: 'fixed', area: 'Kolekcja', text: 'Tworzenie nowego klasera nie kończy się już błędem, a konta, którym przy rejestracji nie utworzyły się startowe klasery, dostają je automatycznie.', textEn: 'Creating a new binder no longer ends in an error, and accounts that didn’t get their starter binders at sign-up now receive them automatically.' },
  { id: '2026-10-08-main-binder', day: '2026-10-08', type: 'improved', area: 'Kolekcja', text: 'Nowe konta zaczynają z jednym „Klaserem Głównym”, którego nie można usunąć ani przemianować; możesz go za to opróżnić z kart przyciskiem „Opróżnij”.', textEn: 'New accounts start with a single “Main binder” that can’t be deleted or renamed; you can, however, clear it of cards with the “Empty” button.' },
  { id: '2026-10-08-catalog-edit', day: '2026-10-08', type: 'fixed', area: 'Kolekcja', text: 'Edycja katalogu (nazwa, opis, kolor, domyślny) znów się zapisuje, a karty przechodzą razem z katalogiem pod nową nazwę.', textEn: 'Editing a binder (name, description, colour, default) saves again, and its cards move along with it under the new name.' },
  { id: '2026-10-08-print-quick-add', day: '2026-10-08', type: 'new', area: 'Karty', text: 'Przy wyborze wydania karty przycisk „Dodaj do kolekcji” od razu dodaje to wydanie do domyślnego klasera.', textEn: 'When choosing a card’s printing, the “Add to collection” button adds that printing straight to your default binder.' },
  { id: '2026-10-08-suggestion-images', day: '2026-10-08', type: 'fixed', area: 'Talie', text: 'W sugestiach EDHREC dla talii Commander znów wczytują się grafiki kart w sekcji „Najczęściej grane, których nie masz w talii”.', textEn: 'In EDHREC suggestions for Commander decks, card images load again in the “Most played cards missing from your deck” section.' },
  { id: '2026-10-08-reset-hasla-email', day: '2026-10-08', type: 'new', area: 'Konto', text: 'Nie pamiętasz hasła? Na ekranie logowania poproś o link na swój adres e-mail i ustaw nowe hasło.', textEn: 'Forgot your password? On the login screen, request a link to your e-mail address and set a new password.' },
  { id: '2026-10-08-potwierdzenie-email', day: '2026-10-08', type: 'new', area: 'Konto', text: 'Nowe konta aktywujesz linkiem wysłanym na adres e-mail podany przy rejestracji.', textEn: 'New accounts are activated with a link sent to the e-mail address given at sign-up.' },
  { id: '2026-10-08-formaty-papierowe', day: '2026-10-08', type: 'new', area: 'Talie', text: 'Nowe formaty talii: Modern, Standard, Pioneer, Legacy, Pauper, Vintage i Premodern.', textEn: 'New deck formats: Modern, Standard, Pioneer, Legacy, Pauper, Vintage and Premodern.' },
  { id: '2026-10-08-formaty-mtga', day: '2026-10-08', type: 'new', area: 'Talie', text: 'Talie do MTG Arena w formatach Pioneer, Historic, Timeless, Alchemy, Brawl, Historic Brawl, Pauper i Artisan.', textEn: 'MTG Arena decks in the Pioneer, Historic, Timeless, Alchemy, Brawl, Historic Brawl, Pauper and Artisan formats.' },
  { id: '2026-10-08-walidacja-formatu', day: '2026-10-08', type: 'new', area: 'Talie', text: 'Talia sprawdza legalność kart, liczbę kopii i liczbę kart według zasad wybranego formatu.', textEn: 'Decks are checked for card legality, number of copies and card count according to the rules of the chosen format.' },
  { id: '2026-10-08-eksport-mtga', day: '2026-10-08', type: 'new', area: 'Talie', text: 'Talie MTG Arena skopiujesz przyciskiem „Eksport do MTGA” i wkleisz w grze przez Importuj.', textEn: 'Copy MTG Arena decks with the “Export to MTGA” button and paste them in the game via Import.' },
  { id: '2026-10-08-karty-arena-szukaj', day: '2026-10-08', type: 'new', area: 'Karty', text: 'W wyszukiwarce kart pole „Karty MTG Arena” pokazuje także karty dostępne tylko w grze cyfrowej.', textEn: 'In card search, the “MTG Arena cards” option also shows cards available only in the digital game.' },
  { id: '2026-10-08-karty-arena-blokada', day: '2026-10-08', type: 'improved', area: 'Karty', text: 'Karty istniejące tylko w MTG Arena nie trafią na sprzedaż ani na listę życzeń.', textEn: 'Cards that exist only in MTG Arena can’t be put up for sale or added to the wishlist.' },
  { id: '2026-10-08-talie-mtga-bez-kolekcji', day: '2026-10-08', type: 'improved', area: 'Talie', text: 'Karty z talii MTG Arena nie dodają się już do kolekcji, bo talie MTGA są cyfrowe.', textEn: 'Cards from MTG Arena decks are no longer added to your collection, since MTGA decks are digital.' },
  { id: '2026-10-08-format-lista-czytelna', day: '2026-10-08', type: 'fixed', area: 'Talie', text: 'Lista formatów w oknie tworzenia talii jest znów czytelna, bez żółtego tekstu na białym tle.', textEn: 'The format list in the deck creation window is readable again, with no more yellow text on a white background.' },
  { id: '2026-10-08-nowa-talia-wszystkie-karty', day: '2026-10-08', type: 'improved', area: 'Talie', text: 'Nowa talia domyślnie korzysta ze wszystkich kart MTG zamiast tylko z Twojej kolekcji.', textEn: 'A new deck now uses all MTG cards by default instead of only your collection.' },
  { id: '2026-10-08-talie-zakladki-formatow', day: '2026-10-08', type: 'new', area: 'Talie', text: 'Lista talii ma zakładki formatów, które pojawiają się, gdy utworzysz pierwszą talię w danym formacie.', textEn: 'The deck list has format tabs, which appear once you create your first deck in a given format.' },
  { id: '2026-10-08-mtga-bez-cen', day: '2026-10-08', type: 'improved', area: 'Talie', text: 'W taliach MTG Arena nie pokazujemy już cen kart przy dodawaniu i przeglądaniu talii.', textEn: 'MTG Arena decks no longer show card prices when adding cards or browsing the deck.' },
  { id: '2026-10-08-mtga-wildcardy', day: '2026-10-08', type: 'new', area: 'Talie', text: 'Talie MTG Arena pokazują, ile wildcardów każdej rzadkości potrzeba, żeby stworzyć talię od zera.', textEn: 'MTG Arena decks show how many wildcards of each rarity you need to build the deck from scratch.' },
  { id: '2026-10-08-mobile-zapis-pod-karta', day: '2026-10-08', type: 'improved', area: 'Telefon', text: 'Na telefonie przycisk zapisu w katalogu jest też tuż pod grafiką karty, więc nie trzeba przewijać do końca.', textEn: 'On phones, the save button in a binder is also right below the card image, so you don’t have to scroll to the bottom.' },
  { id: '2026-10-08-kolekcja-widok-dodatkow', day: '2026-10-08', type: 'new', area: 'Kolekcja', text: 'Nowy widok „Dodatki” w kolekcji: siatka symboli dodatków, z których masz karty, z procentem skompletowania, a po kliknięciu lista kart z wybranego dodatku.', textEn: 'A new “Sets” view in your collection: a grid of symbols of the sets you own cards from, with completion percentages; click one to see the cards from that set.' },
  { id: '2026-10-08-mobile-skaner-prostszy', day: '2026-10-08', type: 'improved', area: 'Skaner', text: 'Prostszy skaner na telefonie: bez wyboru kamery i wgrywania zdjęć, z przyciskiem „Zeskanuj” na środku.', textEn: 'A simpler scanner on phones: no camera choice or photo uploads, with a “Scan” button in the middle.' },
  { id: '2026-10-08-logowanie-nowe-funkcje', day: '2026-10-08', type: 'improved', area: 'Logowanie', text: 'Strona logowania przedstawia nowości: widok kolekcji według dodatków oraz talie w każdym formacie, także do MTG Arena.', textEn: 'The login page presents what’s new: the collection view by set and decks in every format, including MTG Arena.' },
  { id: '2026-10-10-podpis-artysty-ilustracje', day: '2026-10-10', type: 'improved', area: 'Karty', text: 'Przy wykadrowanych ilustracjach kart, np. na liście talii i przy dowódcy, widać teraz nazwisko artysty i informację o prawach Wizards of the Coast.', textEn: 'Cropped card illustrations, such as on the deck list and next to the commander, now show the artist’s name and the Wizards of the Coast copyright notice.' },
  { id: '2026-10-10-pelne-karty-stopka-artysty', day: '2026-10-10', type: 'improved', area: 'Karty', text: 'Obrazy kart pokazujemy w całości, a etykiety z ceną i rankingiem nie zasłaniają już stopki z nazwiskiem artysty.', textEn: 'Card images are shown in full, and price and ranking labels no longer cover the card footer with the artist’s name.' },
  { id: '2026-10-10-nota-fan-content', day: '2026-10-10', type: 'improved', area: 'Aplikacja', text: 'Stopka aplikacji oraz publiczne strony talii i list życzeń zawierają informację, że Mana Screw to nieoficjalny Fan Content, a prawa do materiałów należą do Wizards of the Coast.', textEn: 'The app footer and the public deck and wishlist pages now state that Mana Screw is unofficial Fan Content and that the materials are property of Wizards of the Coast.' },
  { id: '2026-10-10-oznaczenia-kart-ustawienia', day: '2026-10-10', type: 'new', area: 'Ustawienia', text: 'W Ustawieniach, w sekcji „Wygląd kart”, możesz włączyć lub wyłączyć nazwę klasera i ranking EDHREC na kartach, a wybór zapisuje się na Twoim koncie.', textEn: 'In Settings, under “Card display”, you can turn the binder name and EDHREC rank on cards on or off, and your choice is saved to your account.' },
  { id: '2026-10-10-oznaczenia-cena-foil', day: '2026-10-10', type: 'new', area: 'Ustawienia', text: 'W sekcji „Wygląd kart” możesz też ukryć cenę i oznaczenie Foil na kartach w kolekcji.', textEn: 'In “Card display” you can also hide the price and the Foil label on cards in your collection.' },
];
